version: '2'

services:
  hub:
    build: .
    image: dingotiles/dingo-standalone-hub
    container_name: hub
    ports: ["5000:5000"]
    command: []
    environment:
      ETCD_URI: "http://root:password@${DOCKER_HOST_IP}:4001"
      ETCD_HOST: ${DOCKER_HOST_IP}
      ETCD_PORT: 4001
      ETCD_PROTOCOL: http
      ETCD_USERNAME: root
      ETCD_PASSWORD: password
      AWS_ACCESS_KEY_ID: ~
      AWS_SECRET_ACCESS_KEY: ~
      WAL_S3_BUCKET: ~
      WALE_S3_ENDPOINT: ~
      WALE_S3_PREFIX: ~
      DATABASE_URL: postgres://postgres:postgres@${DOCKER_HOST_IP}:5001/postgres
    depends_on: [postgres,etcd]
  cluster1-node1:
    image: dingotiles/dingo-postgresql:pre-test
    container_name: cluster1-node1
    ports: ["5432:5432", "8008:8008"]
    environment:
      DINGO_NODE: node1
      DINGO_CLUSTER: cluster1
      DINGO_ACCOUNT: test-org
      DINGO_API_URI: http://${DOCKER_HOST_IP}:5000
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      DOCKER_HOST_PORT_5432: 5432
      DOCKER_HOST_PORT_8008: 8008
      CELL_GUID: cell1
    depends_on: [etcd,hub]
    command: ["/scripts/entry.sh"]
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v2.3.7
    ports: ["4001:4001", "2380:2380", "2379:2379"]
    command:
    - -name=etcd0
    - -advertise-client-urls=http://${DOCKER_HOST_IP}:2379,http://${DOCKER_HOST_IP}:4001
    - -listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
    - -initial-advertise-peer-urls=http://${DOCKER_HOST_IP}:2380
    - -listen-peer-urls=http://0.0.0.0:2380
    - -initial-cluster-token=etcd-cluster-1
    - -initial-cluster=etcd0=http://${DOCKER_HOST_IP}:2380
    - -initial-cluster-state=new
  postgres:
    # https://hub.docker.com/_/postgres/
    image: postgres
    container_name: postgres
    ports: ["5001:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  # tests:
  #   build: ./images/tests/
  #   image: dingo-api-container-tests
  #   environment:
  #     TEST_PATRONI_SCOPES: "cluster1"
  #     DOCKER_HOST_IP:
  #     ETCD_URI: "http://root:password@${DOCKER_HOST_IP}:4001"
  #     ETCD_HOST: ${DOCKER_HOST_IP}
  #     ETCD_PORT: 4001
  #     ETCD_PROTOCOL: http
  #     ETCD_USERNAME: root
  #     ETCD_PASSWORD: password
  #     DINGO_CLUSTER: cluster1
  #     PATRONI_SCOPE: cluster1
  #     AWS_ACCESS_KEY_ID: ~
  #     AWS_SECRET_ACCESS_KEY: ~
  #     WAL_S3_BUCKET: ~
  #     AWS_REGION: ~
  #     APPUSER_USERNAME: appuser-username
  #     APPUSER_PASSWORD: appuser-password
  #     SUPERUSER_USERNAME: superuser-username
  #     SUPERUSER_PASSWORD: superuser-password
  #     ADMIN_PASSWORD: admin-password
