---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-standalone-hub-pipeline}

inputs:
- name: app-ci
- name: app-gemfile

outputs:
- name: dockerfile

run:
  path: ./app-ci/ci/tasks/copy-gemfile.sh
