---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: api-ci
- name: api

outputs:
- name: app_with_assets

run:
  path: ./api-ci/ci/tasks/generate-assets.sh
