---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-standalone-hub-base}

inputs:
- name: app-ci
- name: app

outputs:
- name: app_with_assets

run:
  path: ./app-ci/ci/tasks/generate-assets.sh
