#!/bin/bash

set -e -x

SUPERUSER_USERNAME=${SUPERUSER_USERNAME:-superuser-username}
SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-superuser-password}

for PATRONI_SCOPE in $TEST_PATRONI_SCOPES; do
  leader_name=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/leader)
  leader_uri=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/members/${leader_name} | jq -r '.conn_url')
  superuser_uri=$(echo ${leader_uri} \
    | sed "s%postgres://%postgres://${SUPERUSER_USERNAME}:${SUPERUSER_PASSWORD}@%")

  psql ${superuser_uri} -c "select pg_switch_xlog();"
done
