#!/bin/bash

set -e -x

if [[ "${ETCD_BROKER_URI:-X}" == "X" ]]; then
  cluster="${ETCD_URI:?required}/v2/keys/service/${PATRONI_SCOPE}"
else
  # Look up /service_instances/xyz for newest
  service_instance_id=$(curl -s ${ETCD_URI:?required}/v2/keys/service_instances | jq -r ".node.nodes | sort_by(.createdIndex) | reverse | first | .key | split(\"/\") | last")
  cluster="${ETCD_URI:?required}/v2/keys/service_instances/${service_instance_id}/service/${PATRONI_SCOPE}"
fi
echo cluster: ${cluster}

leader_name=$(curl -sk ${cluster}/leader | jq -r '.node.value')
leader_uri=$(curl -sk ${cluster}/members/${leader_name} | jq -r '.node.value' | jq -r '.conn_url')
superuser_uri=$(echo ${leader_uri} \
  | sed "s%postgres://%postgres://${SUPERUSER_USERNAME}:${SUPERUSER_PASSWORD}@%")

psql ${superuser_uri} -c "select pg_switch_xlog();"
