#!/bin/bash

set -e -u

for PATRONI_SCOPE in $TEST_PATRONI_SCOPES; do
  echo "Deleting all backups for cluster '${PATRONI_SCOPE}'..."
  region=$(aws s3api get-bucket-location --bucket ${WAL_S3_BUCKET} | jq -r '.LocationConstraint')
  if [[ ${region} != 'null' ]]; then
    region_option="--region ${region}"
  fi

  set -x
  aws s3 ${region_option:-} rm --recursive "s3://${WAL_S3_BUCKET}/backups/${PATRONI_SCOPE}"
done
