#!/bin/bash

set -x -u

if [[ "${ETCD_BROKER_URI:-X}" == "X" ]]; then
  cluster="${ETCD_URI:?required}/v2/keys/service/${PATRONI_SCOPE}"
else
  # Look up /service_instances/xyz for newest
  service_instance_id=$(curl -s ${ETCD_URI:?required}/v2/keys/service_instances | jq -r ".node.nodes | sort_by(.createdIndex) | reverse | first | .key | split(\"/\") | last")
  cluster="${ETCD_URI:?required}/v2/keys/service_instances/${service_instance_id}/service/${PATRONI_SCOPE}"
fi
echo cluster: ${cluster}

curl -XDELETE "${cluster}?dir=true&recursive=true"
