#!/bin/bash

set -e -u

table_name=$1
value=$2

if [[ "${ETCD_BROKER_URI:-X}" == "X" ]]; then
  cluster="${ETCD_URI:?required}/v2/keys/service/${PATRONI_SCOPE}"
else
  # Look up /service_instances/xyz for newest
  service_instance_id=$(curl -s ${ETCD_URI:?required}/v2/keys/service_instances | jq -r ".node.nodes | sort_by(.createdIndex) | reverse | first | .key | split(\"/\") | last")
  cluster="${ETCD_URI:?required}/v2/keys/service_instances/${service_instance_id}/service/${PATRONI_SCOPE}"
fi
echo cluster: ${cluster}

leader_name=$(curl -sk ${cluster}/leader | jq -r '.node.value')
leader_uri=$(curl -sk ${cluster}/members/${leader_name} | jq -r '.node.value' | jq -r '.conn_url')
uri=$(echo ${leader_uri} \
  | sed "s%postgres://%postgres://${APPUSER_USERNAME}:${APPUSER_PASSWORD}@%")

echo "Storing ${value} in ${table_name}..."

psql ${uri} -c "DROP TABLE IF EXISTS ${table_name};"
psql ${uri} -c "CREATE TABLE ${table_name}(value text);"
psql ${uri} -c "INSERT INTO ${table_name} VALUES ('${value}');"
psql ${uri} -c "SELECT value FROM ${table_name};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
  exit 1
}
