---
groups:
- name: deploy
  jobs: [deploy-prod]
- name: images
  jobs: [build-base-image, build-pipeline-image]

jobs:
- name: deploy-prod
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: app}
    - {get: app-ci}
  - task: assert-matching-env
    file: app-ci/ci/tasks/assert-matching-env.yml
    params:
      prod_env_vars: ETCD_BROKER_PLAN_ID,ETCD_BROKER_SERVICE_ID,ETCD_BROKER_URI,S3_BROKER_PASSWORD,S3_BROKER_PLAN_ID,S3_BROKER_SERVICE_ID,S3_BROKER_URL,S3_BROKER_USERNAME
      staging_cf_api: {{cf_staging_api}}
      staging_cf_username: {{cf_staging_username}}
      staging_cf_password: {{cf_staging_password}}
      staging_cf_organization: {{cf_staging_org}}
      staging_cf_space: {{cf_staging_space}}
      staging_cf_skip_cert_check: false
      staging_cf_appname: dingo-api

  - task: generate-assets
    file: app-ci/ci/tasks/generate-assets.yml
  - put: deploy-prod
    params:
      manifest: app/manifest.yml
      path: app_with_assets
      current_app_name: dingo-api
      environment_variables:
        ETCD_BROKER_PLAN_ID: 5bcfa502-f7c0-11e6-bd06-e323138af97b
        ETCD_BROKER_SERVICE_ID: 5b0ad2fe-f7c0-11e6-8e76-7fc33eaeccd4
        ETCD_BROKER_URI: {{cf_prod_etcd_broker_uri}}
        S3_BROKER_URL: {{cf_prod_s3_broker_url}}
        S3_BROKER_USERNAME: {{cf_prod_s3_broker_username}}
        S3_BROKER_PASSWORD: {{cf_prod_s3_broker_password}}
        S3_BROKER_SERVICE_ID: amazon-s3
        S3_BROKER_PLAN_ID: bucket

- name: build-base-image
  public: true
  serial: true
  plan:
  - {get: app-ci}
  - {get: app-gemfile, trigger: true}
  - task: copy-gemfile
    file: app-ci/ci/tasks/copy-gemfile.yml
  - put: docker-base-image
    params:
      build: dockerfile

- name: build-pipeline-image
  public: true
  serial: true
  plan:
  - get: app-ci
  - put: docker-pipeline-image
    params:
      build: app-ci/ci/image

resources:
- name: app
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: app-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: app-gemfile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [Gemfile*]

- name: deploy-prod
  type: cf
  source:
    api: {{cf_prod_api}}
    username: {{cf_prod_username}}
    password: {{cf_prod_password}}
    organization: {{cf_prod_org}}
    space: {{cf_prod_space}}
    skip_cert_check: false

- name: docker-pipeline-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-standalone-hub-pipeline

- name: docker-base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-standalone-hub-base
