---
groups:
- name: deploy
  jobs: [deploy-prod]
- name: ci-image
  jobs: [build-task-image]

jobs:
- name: deploy-prod
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: app, trigger: true}
    - {get: app-ci}
  - task: generate-assets
    file: app-ci/ci/tasks/generate-assets.yml
  - put: deploy-prod
    params:
      manifest: app/manifest.yml
      path: app_with_assets
      current_app_name: dingo-api
      environment_variables:
        ETCD_URI: {{cf_prod_env_etcd_uri}}
        ETCD_HOST_PORT: {{cf_prod_env_etcd_host_port}}
        ETCD_PROTOCOL: {{cf_prod_env_etcd_protocol}}
        ETCD_USERNAME: {{cf_prod_env_etcd_username}}
        ETCD_PASSWORD: {{cf_prod_env_etcd_password}}
        S3_BROKER_URL: {{cf_prod_s3_broker_url}}
        S3_BROKER_USERNAME: {{cf_prod_s3_broker_username}}
        S3_BROKER_PASSWORD: {{cf_prod_s3_broker_password}}
        S3_BROKER_SERVICE_ID: {{cf_prod_s3_broker_service_id}}
        S3_BROKER_PLAN_ID: {{cf_prod_s3_broker_plan_id}}

- name: build-task-image
  public: true
  serial: true
  plan:
  - {get: app-ci}
  - {get: app-gemfile, trigger: true}
  - task: copy-gemfile
    file: app-ci/ci/tasks/copy-gemfile.yml
  - put: docker-image-ci
    params:
      build: dockerfile

resources:
- name: app
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: app-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: app-gemfile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-standalone-hub.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [Gemfile*]

- name: deploy-prod
  type: cf
  source:
    api: {{cf_prod_api}}
    username: {{cf_prod_username}}
    password: {{cf_prod_password}}
    organization: {{cf_prod_org}}
    space: {{cf_prod_space}}
    skip_cert_check: false

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-standalone-hub-pipeline
